# Generated by Django 3.0.4 on 2020-03-17 16:04

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='name',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('Adam', 'Adam'), ('Bartek', 'Bartek'), ('Paweł', 'Paweł'), ('Mateusz', 'Mateusz')], max_length=25),
        ),
    ]
